### ISSUE TITLE
Crash/freeze when holding increase/decrease button

### ISSUE THREAD

**Issue by cbRoy** [TeamClouds/vtc-VaporWare#3]
While in volt mode, holding increase or decrease button cause device to freeze. Screen stays on, but buttons are unresponsive. Battery pull is the only way to get it back.

**Comment by ReservedField** [comment]
I tried to reproduce, didn't succeed. I don't know if @s0be can, but just in case let's check if it's some loop or a legitimate crash.

Pull the `thread` branch from upstream `evic-sdk` (not stable yet, but it has an handy fault tool). Compile it with fault handling enabled and debug info:

```
EVICSDK_FAULT_HANDLER=1 CFLAGS=-g make clean all
```

Now let's compile VaporWare.
Since the patch to fix stack explosion on menus is not pushed yet, open `src/main.c` and add this after the other includes:

```
#include <Thread.h>
THREAD_MAIN_STACKSIZE(2048);
```

Now rebuild both the binary and the ELF file with the new SDK, with debugging info and linker map:

```
EVICSDK=/path/to/evic-sdk CFLAGS=-g LDFLAGS=-Map=ldmap.map make clean all
EVICSDK=/path/to/evic-sdk CFLAGS=-g LDFLAGS=-Map=ldmap.map make atomizer.elf
```

(binary first, ELF last, otherwise it gets removed)

Now you can try reproducing the bug. If it was a crash a screen full of hex numbers will pop up. Report _exactly_ what's on the screen and attach `bin/atomizer.elf` and `ldmap.map`. If it just freezes, then it's likely an infinite loop of some sorts (no need to send any file) and @s0be has probably a better idea as what it is.
By the way, go back to normal SDK after doing this (and remove the `main.c` patch), since the `thread` branch is not ready yet.

**Comment by cbRoy** [comment]
Awesome I will do this when I get home.

Last night me and s0be played with it and finally got it working.

I built with teamclouds/evic-sdk on pats-bs branch and also vaporware Pat's
branch with gcc 5.4 ( was using 4.8.2, not sure if this actually helped
any).

Pat's vaporware branch had the same issue on your master SDK though so I'll
pull the thread branch and build on that and post results.

**Comment by cbRoy** [comment]
This was my dumb fault. From when I added support for faster increasing and decreasing, I never modified mode_volt.c or mode_temp.c to not change, so everything i held the button it was looking for methods that didn't exist. 

Close, and sorry for all the confusion. I could've sworn this happened before that, but I guess not. 

Thanks for all the help s0be and suggestions ReservedField.
